services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DataBaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DataBaseSettings__DatabaseName=CatalogDb"
      - "DataBaseSettings__ProductCollectionName=Products"
      - "DataBaseSettings__BrandCollectionName=Brands"
      - "DataBaseSettings__TypeCollectionName=Types"
    depends_on:
      - catalogdb
    ports:
      - "8080:8080"
    
